version: '{build}'
os: Visual Studio 2015
configuration: Release
platform: x64

environment:
  DOWNLOAD_APIKEY:
    secure: SEKmgfhiwujukYrr2xjqp63FEwvDUcoQOy7pCuYSyu+CTbGRRIzTbUCwwu4EPJmE
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

branches:
  except:
    - coverity_scan # No need for Windows builds on that branch

cache: c:\tools\vcpkg\installed -> appveyor64.yml

before_build:
- cmd: |
    echo Installing dependencies...
    vcpkg integrate install
    #copy mk\cmake\x64-windows.cmake C:\tools\vcpkg\triplets\
    vcpkg install boost-date-time:x64-windows
    vcpkg install boost-filesystem:x64-windows
    vcpkg install boost-format:x64-windows
    vcpkg install boost-locale:x64-windows
    vcpkg install boost-optional:x64-windows
    vcpkg install boost-system:x64-windows
    vcpkg install curl:x64-windows
    vcpkg install glew:x64-windows
    vcpkg install libogg:x64-windows
    vcpkg install libvorbis:x64-windows
    vcpkg install openal-soft:x64-windows
    vcpkg install sdl2:x64-windows
    vcpkg install sdl2-image:x64-windows
    git submodule update --init --recursive
    echo Running cmake ..
    cmake -G "Visual Studio 14 2015 Win64" -DVCPKG_BUILD=ON -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=%P% -DHAVE_SDL=true -DPACKAGE_VCREDIST=true

build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: detailed

after_build:
- cmd: '"C:\Program Files (x86)\CMake\bin\cpack.exe"'
- ps: |
    Write-Output Get-FileHash SuperTux-*
    
    function transfer ($filename)
    {
        $file = Get-Item $filename;
        invoke-webrequest -method put -infile $file.FullName https://transfer.sh/$($file.Name)
    }
    
    if(-not $Env:APPVEYOR_PULL_REQUEST_NUMBER) {
      foreach ($path in get-ChildItem SuperTux-*) {
      
        $response = transfer($path)
        $url = $response.Content
        $file = Get-Item $path;
        $shasum = Get-FileHash $file -Algorithm SHA256
      
        $postParams = @{
          apikey=$Env:DOWNLOAD_APIKEY;
          size=$file.length;
          url=$url;
          branch=$Env:APPVEYOR_REPO_BRANCH;
          shasum = $shasum.Hash
        }
        Invoke-WebRequest -Uri https://download.supertux.org/submit.php -Method POST -Body $postParams
      }
    }

test: off

artifacts:
- path: SuperTux-*
  name: setup

deploy:
- provider: GitHub
  description: 'SuperTux release'
  auth_token:
    secure: 1sgroG7ycKHC6R2y/V7DECd/SHxXK4CNSDU7zZOnAlyBiVKT9ykvRKWt2DGcEZDq
  artifact: setup
  draft: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
#- provider: BinTray
#  username: maths22
#  api_key:
#    secure: 9miH0V65c10cbWfovqIfIHWsbyrg6jZDnaYxyGYHF5pyQbPnS+LcIX6Y/8gK2pM4
#  subject: supertux
#  repo: SuperTux-Nightly
#  package: win64
#  publish: true
#  override: true
#  on:
#    branch: master
